// GENERATED by @edgedb/generate v__@edgedb/generate__VERSION_PLACEHOLDER__

export * as edgedb from "edgedb";
export { spec } from "./__spec__.ts";
export * as syntax from "./syntax.ts";
export * as castMaps from "./castMaps.ts";
