name: Deploy

on:
  push:
    branches: [version-1-edgedb-cloud-setup]
  pull_request:
    branches: [version-1-edgedb-cloud-setup]

jobs:
  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest

    env:
      EDGEDB_CLIENT_TLS_SECURITY: insecure

    permissions:
      id-token: write         # Required for authentication with Deno Deploy
      contents: read          # Required to clone the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0

      - name: Set EDGEDB Environment Variables
        run: |
          echo "EDGEDB_DSN=${{ secrets.EDGEDB_DSN }}" >> $GITHUB_ENV

      - name: Run Build Task
        run: deno task build

      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: "stinstewmil-starter-den-94"
          entrypoint: "main.ts"