// GENERATED by @edgedb/generate v__@edgedb/generate__VERSION_PLACEHOLDER__

import * as $ from "../reflection.ts";
import * as _ from "../imports.ts";
import _module__ai from "./ext/ai.ts";
import _module__pgvector from "./ext/pgvector.ts";


type __defaultExports = {
  "ai": typeof _module__ai;
  "pgvector": typeof _module__pgvector
};
const __defaultExports: __defaultExports = {
  "ai": _module__ai,
  "pgvector": _module__pgvector
};
export default __defaultExports;
